### ISSUE TITLE
Implement Cldr.Territory select function.

### ISSUE THREAD

**Issue by Schultzer** [elixir-cldr/cldr_html#4]
Kipp you can just assign me on this I will work this out when we done with `currency_select`

### Ideas to Territory select functions

- [ ] `territory_select`
- [ ] `phone_select` note: I'm not sure if this is useful enough to be added

**Comment by kipcole9** [comment]
I've done a bit of refactoring on the code, done some work on the code docs and I think its in reasonable shape.

What I plan to do next is to see how much of the option parsing I can refactor out so that multiple selects can use them since `locale` will be common and `select` will have a common strategy to validate and add to the select list if required.

I need to work on the README and CHANGELOG (I will manually add the content you kindly wrote in your PR since it won't merge now with the changed I've made).

**Comment by kipcole9** [comment]
As of May 23, 2021, version 0.3.0 supports territory selection.  The changelog entry is:

### Enhancements

* Add `Cldr.HTML.Territory.select/3` to select territories

* Add support for `:style` option in `Cldr.HTML.Unit.select/3`
*
